# Generated by Django 3.0.8 on 2020-07-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbonhydrate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('carlorie', models.DecimalField(decimal_places=3, max_digits=5)),
                ('carcium', models.DecimalField(decimal_places=3, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=3, max_digits=5)),
                ('caffein', models.DecimalField(decimal_places=3, max_digits=5)),
                ('dd', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
