# Generated by Django 3.0.8 on 2020-07-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='carcium',
            new_name='calcium',
        ),
    ]
