# Generated by Django 3.0.8 on 2020-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_auto_20200728_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='caffein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calcium',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbonhydrate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carlorie',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.IntegerField(),
        ),
    ]
