# Generated by Django 3.0.8 on 2020-07-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0004_auto_20200728_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='dd',
            new_name='salt',
        ),
    ]
