# Generated by Django 3.0.6 on 2020-07-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0006_auto_20200731_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Cholesterol',
            new_name='cholesterol',
        ),
    ]
